/* Generated with Xl_to_SQL.py -- Patricio Labin Correa
====================================================================*/
INSERT INTO tipo_legislador VALUES (1,"Senador",TRUE);
INSERT INTO tipo_legislador VALUES (2,"Diputado",TRUE);

INSERT INTO tipo_usuario VALUES (1,"Administrador",1);
INSERT INTO tipo_usuario VALUES (2,"Usuario",1);
INSERT INTO tipo_usuario VALUES (3,"Editor",1);

INSERT INTO region VALUES (1,"XV","Arica y Parinacota",TRUE);
INSERT INTO region VALUES (2,"I","Tarapacá",TRUE);
INSERT INTO region VALUES (3,"II","Antofagasta",TRUE);
INSERT INTO region VALUES (4,"III","Atacama",TRUE);
INSERT INTO region VALUES (5,"IV","Coquimbo",TRUE);
INSERT INTO region VALUES (6,"V","Valparaíso",TRUE);
INSERT INTO region VALUES (7,"RM","Metropolitana de Santiago",TRUE);
INSERT INTO region VALUES (8,"VI","del Libertador Gral. Bernardo O’Higgins",TRUE);
INSERT INTO region VALUES (9,"VII","del Maule",TRUE);
INSERT INTO region VALUES (10,"VIII","del Bío-Bío",TRUE);
INSERT INTO region VALUES (11,"IX","de la Araucanía",TRUE);
INSERT INTO region VALUES (12,"XVI","de Los Ríos",TRUE);
INSERT INTO region VALUES (13,"X","de Los Lagos",TRUE);
INSERT INTO region VALUES (14,"XI","Aisén del Gral. Carlos Ibáñez del Campo",TRUE);
INSERT INTO region VALUES (15,"XII","de Magallanes y de la Antártica Chilena",TRUE);
INSERT INTO region VALUES (16,"Ñ","de Ñuble",TRUE);

INSERT INTO partido_politico VALUES (1,"Unión Demócrata Independiente",NULL,1);
INSERT INTO partido_politico VALUES (2,"Renovación Nacional",NULL,1);
INSERT INTO partido_politico VALUES (3,"Partido Socialista de Chile",NULL,1);
INSERT INTO partido_politico VALUES (4,"Partido Demócrata Cristiano",NULL,1);
INSERT INTO partido_politico VALUES (5,"Partido por la Democracia",NULL,1);
INSERT INTO partido_politico VALUES (6,"Evolución Política",NULL,1);
INSERT INTO partido_politico VALUES (7,"Revolución Democrática",NULL,1);
INSERT INTO partido_politico VALUES (8,"Partido Radical Socialdemócrata",NULL,1);
INSERT INTO partido_politico VALUES (9,"Por la Integración Regional",NULL,1);
INSERT INTO partido_politico VALUES (10,"País",NULL,1);
INSERT INTO partido_politico VALUES (11,"Partido Comunista de Chile",NULL,1);
INSERT INTO partido_politico VALUES (12,"Partido Humanista",NULL,1);
INSERT INTO partido_politico VALUES (13,"Federación Regionalista Verde Social",NULL,1);
INSERT INTO partido_politico VALUES (14,"Partido Liberal de Chile",NULL,1);
INSERT INTO partido_politico VALUES (15,"Partido Progresista",NULL,1);
INSERT INTO partido_politico VALUES (16,"Partido Ecologista Verde",NULL,1);
INSERT INTO partido_politico VALUES (17,"Poder Ciudadano",NULL,1);
INSERT INTO partido_politico VALUES (18,"Partido Igualdad",NULL,1);
INSERT INTO partido_politico VALUES (19,"Partido Regionalista Independiente",NULL,1);
INSERT INTO partido_politico VALUES (20,"Amplitud",NULL,1);
INSERT INTO partido_politico VALUES (21,"MAS-Región",NULL,1);
INSERT INTO partido_politico VALUES (22,"Izquierda Ciudadana de Chile",NULL,1);
INSERT INTO partido_politico VALUES (23,"Democracia Regional Patagónica",NULL,1);
INSERT INTO partido_politico VALUES (24,"ANDHA Chile",NULL,1);
INSERT INTO partido_politico VALUES (25,"Unión Patriótica",NULL,1);
INSERT INTO partido_politico VALUES (26,"Todos",NULL,1);
INSERT INTO partido_politico VALUES (27,"Ciudadanos",NULL,1);
INSERT INTO partido_politico VALUES (28,"Partido de Trabajadores Revolucionarios",NULL,1);
INSERT INTO partido_politico VALUES (9999,"Independiente","logo.gif",1);

INSERT INTO estado_noticioso VALUES (1,"No Relevante",TRUE);
INSERT INTO estado_noticioso VALUES (2,"Involucrado en proceso judicial",TRUE);

INSERT INTO circunscripcion VALUES (1,1,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (2,2,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (3,3,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (4,4,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (5,5,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (6,6,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (7,7,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (8,8,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (9,9,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (10,10,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (11,11,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (12,12,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (13,13,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (14,14,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (15,15,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (16,16,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (17,17,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (18,18,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (19,19,TRUE,TRUE);
INSERT INTO circunscripcion VALUES (20,1,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (21,2,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (22,3,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (23,4,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (24,5,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (25,6,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (26,7,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (27,8,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (28,9,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (29,10,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (30,11,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (31,12,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (32,13,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (33,14,FALSE,TRUE);
INSERT INTO circunscripcion VALUES (34,15,FALSE,TRUE);

INSERT INTO distrito VALUES (1,1,TRUE,TRUE);
INSERT INTO distrito VALUES (2,2,TRUE,TRUE);
INSERT INTO distrito VALUES (3,3,TRUE,TRUE);
INSERT INTO distrito VALUES (4,4,TRUE,TRUE);
INSERT INTO distrito VALUES (5,5,TRUE,TRUE);
INSERT INTO distrito VALUES (6,6,TRUE,TRUE);
INSERT INTO distrito VALUES (7,7,TRUE,TRUE);
INSERT INTO distrito VALUES (8,8,TRUE,TRUE);
INSERT INTO distrito VALUES (9,9,TRUE,TRUE);
INSERT INTO distrito VALUES (10,10,TRUE,TRUE);
INSERT INTO distrito VALUES (11,11,TRUE,TRUE);
INSERT INTO distrito VALUES (12,12,TRUE,TRUE);
INSERT INTO distrito VALUES (13,13,TRUE,TRUE);
INSERT INTO distrito VALUES (14,14,TRUE,TRUE);
INSERT INTO distrito VALUES (15,15,TRUE,TRUE);
INSERT INTO distrito VALUES (16,16,TRUE,TRUE);
INSERT INTO distrito VALUES (17,17,TRUE,TRUE);
INSERT INTO distrito VALUES (18,18,TRUE,TRUE);
INSERT INTO distrito VALUES (19,19,TRUE,TRUE);
INSERT INTO distrito VALUES (20,20,TRUE,TRUE);
INSERT INTO distrito VALUES (21,21,TRUE,TRUE);
INSERT INTO distrito VALUES (22,22,TRUE,TRUE);
INSERT INTO distrito VALUES (23,23,TRUE,TRUE);
INSERT INTO distrito VALUES (24,24,TRUE,TRUE);
INSERT INTO distrito VALUES (25,25,TRUE,TRUE);
INSERT INTO distrito VALUES (26,26,TRUE,TRUE);
INSERT INTO distrito VALUES (27,27,TRUE,TRUE);
INSERT INTO distrito VALUES (28,28,TRUE,TRUE);
INSERT INTO distrito VALUES (29,29,TRUE,TRUE);
INSERT INTO distrito VALUES (30,30,TRUE,TRUE);
INSERT INTO distrito VALUES (31,31,TRUE,TRUE);
INSERT INTO distrito VALUES (32,32,TRUE,TRUE);
INSERT INTO distrito VALUES (33,33,TRUE,TRUE);
INSERT INTO distrito VALUES (34,34,TRUE,TRUE);
INSERT INTO distrito VALUES (35,35,TRUE,TRUE);
INSERT INTO distrito VALUES (36,36,TRUE,TRUE);
INSERT INTO distrito VALUES (37,37,TRUE,TRUE);
INSERT INTO distrito VALUES (38,38,TRUE,TRUE);
INSERT INTO distrito VALUES (39,39,TRUE,TRUE);
INSERT INTO distrito VALUES (40,40,TRUE,TRUE);
INSERT INTO distrito VALUES (41,41,TRUE,TRUE);
INSERT INTO distrito VALUES (42,42,TRUE,TRUE);
INSERT INTO distrito VALUES (43,43,TRUE,TRUE);
INSERT INTO distrito VALUES (44,44,TRUE,TRUE);
INSERT INTO distrito VALUES (45,45,TRUE,TRUE);
INSERT INTO distrito VALUES (46,46,TRUE,TRUE);
INSERT INTO distrito VALUES (47,47,TRUE,TRUE);
INSERT INTO distrito VALUES (48,48,TRUE,TRUE);
INSERT INTO distrito VALUES (49,49,TRUE,TRUE);
INSERT INTO distrito VALUES (50,50,TRUE,TRUE);
INSERT INTO distrito VALUES (51,51,TRUE,TRUE);
INSERT INTO distrito VALUES (52,52,TRUE,TRUE);
INSERT INTO distrito VALUES (53,53,TRUE,TRUE);
INSERT INTO distrito VALUES (54,54,TRUE,TRUE);
INSERT INTO distrito VALUES (55,55,TRUE,TRUE);
INSERT INTO distrito VALUES (56,56,TRUE,TRUE);
INSERT INTO distrito VALUES (57,57,TRUE,TRUE);
INSERT INTO distrito VALUES (58,58,TRUE,TRUE);
INSERT INTO distrito VALUES (59,59,TRUE,TRUE);
INSERT INTO distrito VALUES (60,60,TRUE,TRUE);
INSERT INTO distrito VALUES (61,1,FALSE,TRUE);
INSERT INTO distrito VALUES (62,2,FALSE,TRUE);
INSERT INTO distrito VALUES (63,3,FALSE,TRUE);
INSERT INTO distrito VALUES (64,4,FALSE,TRUE);
INSERT INTO distrito VALUES (65,5,FALSE,TRUE);
INSERT INTO distrito VALUES (66,6,FALSE,TRUE);
INSERT INTO distrito VALUES (67,7,FALSE,TRUE);
INSERT INTO distrito VALUES (68,8,FALSE,TRUE);
INSERT INTO distrito VALUES (69,9,FALSE,TRUE);
INSERT INTO distrito VALUES (70,10,FALSE,TRUE);
INSERT INTO distrito VALUES (71,11,FALSE,TRUE);
INSERT INTO distrito VALUES (72,12,FALSE,TRUE);
INSERT INTO distrito VALUES (73,13,FALSE,TRUE);
INSERT INTO distrito VALUES (74,14,FALSE,TRUE);
INSERT INTO distrito VALUES (75,15,FALSE,TRUE);
INSERT INTO distrito VALUES (76,16,FALSE,TRUE);
INSERT INTO distrito VALUES (77,17,FALSE,TRUE);
INSERT INTO distrito VALUES (78,18,FALSE,TRUE);
INSERT INTO distrito VALUES (79,19,FALSE,TRUE);
INSERT INTO distrito VALUES (80,20,FALSE,TRUE);
INSERT INTO distrito VALUES (81,21,FALSE,TRUE);
INSERT INTO distrito VALUES (82,22,FALSE,TRUE);
INSERT INTO distrito VALUES (83,23,FALSE,TRUE);
INSERT INTO distrito VALUES (84,24,FALSE,TRUE);
INSERT INTO distrito VALUES (85,25,FALSE,TRUE);
INSERT INTO distrito VALUES (86,26,FALSE,TRUE);
INSERT INTO distrito VALUES (87,27,FALSE,TRUE);
INSERT INTO distrito VALUES (88,28,FALSE,TRUE);

INSERT INTO circunscripcion_distrito VALUES (1,1);
INSERT INTO circunscripcion_distrito VALUES (2,1);
INSERT INTO circunscripcion_distrito VALUES (3,2);
INSERT INTO circunscripcion_distrito VALUES (4,2);
INSERT INTO circunscripcion_distrito VALUES (5,3);
INSERT INTO circunscripcion_distrito VALUES (6,3);
INSERT INTO circunscripcion_distrito VALUES (7,4);
INSERT INTO circunscripcion_distrito VALUES (8,4);
INSERT INTO circunscripcion_distrito VALUES (9,4);
INSERT INTO circunscripcion_distrito VALUES (10,5);
INSERT INTO circunscripcion_distrito VALUES (11,5);
INSERT INTO circunscripcion_distrito VALUES (12,5);
INSERT INTO circunscripcion_distrito VALUES (13,6);
INSERT INTO circunscripcion_distrito VALUES (14,6);
INSERT INTO circunscripcion_distrito VALUES (15,6);
INSERT INTO circunscripcion_distrito VALUES (16,7);
INSERT INTO circunscripcion_distrito VALUES (17,7);
INSERT INTO circunscripcion_distrito VALUES (18,7);
INSERT INTO circunscripcion_distrito VALUES (19,7);
INSERT INTO circunscripcion_distrito VALUES (20,7);
INSERT INTO circunscripcion_distrito VALUES (22,7);
INSERT INTO circunscripcion_distrito VALUES (30,7);
INSERT INTO circunscripcion_distrito VALUES (31,7);
INSERT INTO circunscripcion_distrito VALUES (21,8);
INSERT INTO circunscripcion_distrito VALUES (23,8);
INSERT INTO circunscripcion_distrito VALUES (24,8);
INSERT INTO circunscripcion_distrito VALUES (25,8);
INSERT INTO circunscripcion_distrito VALUES (26,8);
INSERT INTO circunscripcion_distrito VALUES (27,8);
INSERT INTO circunscripcion_distrito VALUES (28,8);
INSERT INTO circunscripcion_distrito VALUES (29,8);
INSERT INTO circunscripcion_distrito VALUES (32,9);
INSERT INTO circunscripcion_distrito VALUES (33,9);
INSERT INTO circunscripcion_distrito VALUES (34,9);
INSERT INTO circunscripcion_distrito VALUES (35,9);
INSERT INTO circunscripcion_distrito VALUES (36,10);
INSERT INTO circunscripcion_distrito VALUES (37,10);
INSERT INTO circunscripcion_distrito VALUES (38,10);
INSERT INTO circunscripcion_distrito VALUES (39,11);
INSERT INTO circunscripcion_distrito VALUES (40,11);
INSERT INTO circunscripcion_distrito VALUES (42,12);
INSERT INTO circunscripcion_distrito VALUES (43,12);
INSERT INTO circunscripcion_distrito VALUES (44,12);
INSERT INTO circunscripcion_distrito VALUES (45,12);
INSERT INTO circunscripcion_distrito VALUES (41,13);
INSERT INTO circunscripcion_distrito VALUES (46,13);
INSERT INTO circunscripcion_distrito VALUES (47,13);
INSERT INTO circunscripcion_distrito VALUES (48,14);
INSERT INTO circunscripcion_distrito VALUES (49,14);
INSERT INTO circunscripcion_distrito VALUES (50,15);
INSERT INTO circunscripcion_distrito VALUES (51,15);
INSERT INTO circunscripcion_distrito VALUES (52,15);
INSERT INTO circunscripcion_distrito VALUES (53,16);
INSERT INTO circunscripcion_distrito VALUES (54,16);
INSERT INTO circunscripcion_distrito VALUES (55,17);
INSERT INTO circunscripcion_distrito VALUES (56,17);
INSERT INTO circunscripcion_distrito VALUES (57,17);
INSERT INTO circunscripcion_distrito VALUES (58,17);
INSERT INTO circunscripcion_distrito VALUES (59,18);
INSERT INTO circunscripcion_distrito VALUES (60,19);
INSERT INTO circunscripcion_distrito VALUES (61,20);
INSERT INTO circunscripcion_distrito VALUES (62,21);
INSERT INTO circunscripcion_distrito VALUES (63,22);
INSERT INTO circunscripcion_distrito VALUES (64,23);
INSERT INTO circunscripcion_distrito VALUES (65,24);
INSERT INTO circunscripcion_distrito VALUES (66,25);
INSERT INTO circunscripcion_distrito VALUES (67,25);
INSERT INTO circunscripcion_distrito VALUES (68,26);
INSERT INTO circunscripcion_distrito VALUES (69,26);
INSERT INTO circunscripcion_distrito VALUES (70,26);
INSERT INTO circunscripcion_distrito VALUES (71,26);
INSERT INTO circunscripcion_distrito VALUES (72,26);
INSERT INTO circunscripcion_distrito VALUES (73,26);
INSERT INTO circunscripcion_distrito VALUES (74,26);
INSERT INTO circunscripcion_distrito VALUES (75,27);
INSERT INTO circunscripcion_distrito VALUES (76,27);
INSERT INTO circunscripcion_distrito VALUES (77,28);
INSERT INTO circunscripcion_distrito VALUES (78,28);
INSERT INTO circunscripcion_distrito VALUES (79,29);
INSERT INTO circunscripcion_distrito VALUES (80,29);
INSERT INTO circunscripcion_distrito VALUES (81,29);
INSERT INTO circunscripcion_distrito VALUES (82,30);
INSERT INTO circunscripcion_distrito VALUES (83,30);
INSERT INTO circunscripcion_distrito VALUES (84,31);
INSERT INTO circunscripcion_distrito VALUES (85,32);
INSERT INTO circunscripcion_distrito VALUES (86,32);
INSERT INTO circunscripcion_distrito VALUES (87,33);
INSERT INTO circunscripcion_distrito VALUES (88,34);

INSERT INTO periodo VALUES (1,"Junta de Gobierno",1973,1981,TRUE);
INSERT INTO periodo VALUES (2,"Junta de Gobierno",1981,1990,TRUE);
INSERT INTO periodo VALUES (3,"XLVIII Período Legislativo del Congreso Nacional",1990,1994,TRUE);
INSERT INTO periodo VALUES (4,"XLIX Período Legislativo del Congreso Nacional",1994,1998,TRUE);
INSERT INTO periodo VALUES (5,"L Período Legislativo del Congreso Nacional",1998,2002,TRUE);
INSERT INTO periodo VALUES (6,"LI Período Legislativo del Congreso Nacional",2002,2006,TRUE);
INSERT INTO periodo VALUES (7,"LII Período Legislativo del Congreso Nacional",2006,2010,TRUE);
INSERT INTO periodo VALUES (8,"LIII Período Legislativo del Congreso Nacional",2010,2014,TRUE);
INSERT INTO periodo VALUES (9,"LIV Período Legislativo del Congreso Nacional",2014,2018,TRUE);
INSERT INTO periodo VALUES (10,"LV Período Legislativo del Congreso Nacional",2018,2022,TRUE);
INSERT INTO periodo VALUES (11,"LVI Período Legislativo del Congreso Nacional",2022,2026,TRUE);

/* Password: admin1234 */
INSERT INTO usuario VALUES (1,1,"admin_test","admin@mail.com","pbkdf2:sha256:50000$d7UdRQg2$fc55347bed76803ebb3dfa6b23ae7162cd9637c92bec55ce9449272757c9230e","2018-02-05 00:00:00","2018-02-05 00:00:00",1);
