"""'mensajes'

Revision ID: c498a6fb8aea
Revises: e07667d84e40
Create Date: 2018-06-24 11:24:15.375423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c498a6fb8aea'
down_revision = 'e07667d84e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=512), nullable=False),
    sa.Column('contenido', sa.String(length=2048), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensaje')
    # ### end Alembic commands ###
