from project_snitch.forms.UserLoginForm import UserLoginForm
from project_snitch.forms.UserRegisterForm import UserRegisterForm
from project_snitch.forms.UserSubscribeForm import UserSubscribeForm
from project_snitch.forms.UserUnsubscribeForm import UserUnsubscribeForm
from project_snitch.forms.UserChangeProfile import UserChangeProfile